# Generated by Django 5.0.4 on 2024-04-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_article_delete_contentelement_delete_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
